### ISSUE TITLE
FiveM Exports receive table instead function

### ISSUE THREAD

**Issue by draobrehtom** [Cyntaax/fivem-fishing#1]
Greetings and thank you for sharing your great work on GitHub! 

Currently I'm in process of testing this resource and I've met an issue which is related to some of updates of FiveM from 2021:
When you use export and pass a callback function, it is received as table. For example:

```lua
-- test/server.lua
exports.fishing:SetGivePlayerItem(function(playerId, item, amount)
    TriggerEvent("test123")
end)
```

```lua
-- fishing/server.lua
exports('SetGivePlayerItem', function(handler)
    if type(handler) == "function" then
        print("Handler set")
        SvFishing.GivePlayerItem = handler
    else
        print("Handler not set", type(handler))
    end
end)
```

```
[      script:fishing] Handler not set  table
```

For a moment I am not sure how to fix this issue. I will continue testing and keep updated about this issue.

**Comment by aethyriion** [comment]
> Greetings and thank you for sharing your great work on GitHub! 
> 
> 
> 
> Currently I'm in process of testing this resource and I've met an issue which is related to some of updates of FiveM from 2021:
> 
> When you use export and pass a callback function, it is received as table. For example:
> 
> 
> 
> ```lua
> 
> -- test/server.lua
> 
> exports.fishing:SetGivePlayerItem(function(playerId, item, amount)
> 
>     TriggerEvent("test123")
> 
> end)
> 
> ```
> 
> 
> 
> ```lua
> 
> -- fishing/server.lua
> 
> exports('SetGivePlayerItem', function(handler)
> 
>     if type(handler) == "function" then
> 
>         print("Handler set")
> 
>         SvFishing.GivePlayerItem = handler
> 
>     else
> 
>         print("Handler not set", type(handler))
> 
>     end
> 
> end)
> 
> ```
> 
> 
> 
> ```
> 
> [      script:fishing] Handler not set  table
> 
> ```
> 
> 
> 
> For a moment I am not sure how to fix this issue. I will continue testing and keep updated about this issue.

Whoops, this was an oversight. I'll just have to get rid of those checks. Thanks for pointing it out!

**Comment by draobrehtom** [comment]
That was a fast reply! I've just tested it without checks and confirming that this will work! Thank you! If you don't mind, I can work on pull request for this issue.

**Comment by aethyriion** [comment]
That would be awesome! Thank you very much
